// smart_city_shanghai/src/views/MapControl/index.tsx
import React, { useContext, useEffect, useState } from "react";
import MapContext from "../../store/map-context";
import { Logo, Zoom, Fullscreen, MouseLocation, MapTheme } from "@antv/l7";

export default function MapControl() {
  const ctx = useContext(MapContext);
  const { map, scene } = ctx;
  const [controlAdded, setControlAdded] = useState(false);

  useEffect(() => {
    if (map && scene && !controlAdded) {
      const logo = new Logo({
        position: "lefttop",
        // 图片 url
        img: "https://img.gejiba.com/images/dfdb6db1623eb881e724f58d9a366af8.png",
        // 跳转地址
        href: "https://zhangouwen.netlify.app/",
      });
      scene.addControl(logo);
      const zoom = new Zoom({
        zoomInTitle: "放大",
        zoomOutTitle: "缩小",
        position: "bottomright",
      });
      scene.addControl(zoom);

      const fullscreen = new Fullscreen({
        btnText: "全屏",
        exitBtnText: "退出全屏",
      });
      scene.addControl(fullscreen);
      // const mouseLocation = new MouseLocation({
      //   transform: (position) => {
      //     return position;
      //   },
      //   position: "rightbottom",
      // });
      // scene.addControl(mouseLocation);
      const mapTheme = new MapTheme({});
      scene.addControl(mapTheme);
      setControlAdded(true);
    }
  }, [map, scene]);

  return <div></div>;
}

// demo/smart-city/src/views/MapControl.vue
<template>
    <div></div>
</template>

<script setup>
import { inject, onMounted } from 'vue'
import { Logo, Zoom, Fullscreen, MouseLocation, MapTheme } from '@antv/l7'
// 依赖注入，拿到L7和mapbox地图实例
const { scene, map } = inject('$scene_map')

onMounted(() => {
    // 标志
    const logo = new Logo({
        position: 'lefttop',
        // 图片 url
        img:
            'https://img.gejiba.com/images/dfdb6db1623eb881e724f58d9a366af8.png',
        // 跳转地址
        href: 'http://www.x-zd.com/',
    });
    scene.addControl(logo)

    // 放大缩小
    const zoom = new Zoom({
        position: 'leftbottom',
        zoomInTitle: '放大',
        zoomOutTitle: '缩小',
        className: 'my-test-class',
    });
    scene.addControl(zoom)

    // 全屏控件
    const fullScreen = new Fullscreen({
        btnText: '全屏',
        exitBtnText: '推出全屏'
    })
    scene.addControl(fullScreen)

    // 鼠标位置控件
    const mouseLoc = new MouseLocation({
        transform: (position) => {
            return position.map(item => item.toFixed(4));
        },
        position:'rightbottom'
    })
    scene.addControl(mouseLoc)

    // 地图主题控件
    const mapTheme=new MapTheme({})
    scene.addControl(mapTheme)
})

</script>
<style scoped></style>
